server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: RAGHUL
    password: 6379362346
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate  # Change to 'update' temporarily if migration fails
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_gateway_service
    out-of-order: true
    clean-disabled: false
    # Ensure migrations run before Hibernate validation
    baseline-version: 0
    baseline-description: "Initial baseline"

# Enable detailed logging for debugging
logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.tool.schema: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: bXlfc3VwZXJfc2VjdXJlX3Rlc3Rfa2V5XzEyMzQ1Njc4OTA=  # Base64 of 32-byte key
  expiration-ms: 3600000

otp:
  provider: 2factor
  base-url: https://2factor.in/API/V1
  api-key: 4b1e1a26-7280-11f0-a562-0200cd936042

services:
  kyc:
    base-url: http://localhost:8084
  customer:
    base-url: http://localhost:8081