CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       username VARCHAR2(100) NOT NULL UNIQUE,
                       role VARCHAR2(20) NOT NULL,
                       password_hash VARCHAR2(255),
                       enabled NUMBER(1) DEFAULT 1 NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
