CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       username VARCHAR2(100) NOT NULL UNIQUE,
                       role VARCHAR2(20) NOT NULL,
                       password_hash VARCHAR2(255),
                       enabled NUMBER(1) DEFAULT 1 NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- V2__insert_admin_user.sql

INSERT INTO users (username, role, password_hash, enabled, created_at)
VALUES (
           'admin',
           'ADMIN',
           '$2a$10$egLPrqZuc3gwk387j3tgCe3jaLYGJbyL50mYnOUNHW7DJbgIL3mVG', -- password: admin123
           1,
           CURRENT_TIMESTAMP
       );
